# Generated by Django 3.2.9 on 2021-12-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_6',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ManyToManyField(blank=True, null=True, to='products.ProductImages'),
        ),
    ]
