# Generated by Django 3.2.9 on 2021-12-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_photo_productimages_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo_main',
        ),
    ]
