# Generated by Django 4.0 on 2021-12-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20211213_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='is_mvp',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
